swagger: "2.0"
info:
  version: "0.0.1"
  title: Hello World App
# during dev, should point to your local machine
host: localhost:10010
# basePath prefixes all resource paths 
basePath: /
# 
schemes:
  # tip: remove http to make production-grade
  - http
  - https
# format of bodies a client can send (Content-Type)
consumes:
  - application/json
# format of the responses to the client (Accepts)
produces:
  - application/json
paths:
  /hello:
    # binds a127 app logic to a route
    x-swagger-router-controller: hello_world
    get:
      description: Returns 'Hello' to the caller
      # used as the method name of the controller
      operationId: hello
      parameters:
        - name: name
          in: query
          description: The name of the person to whom to say hello
          required: false
          type: string
      responses:
        "200":
          description: Success
          schema:
            # a pointer to a definition
            $ref: "#/definitions/HelloWorldResponse"
        # responses may fall through to errors
        default:
          description: Error
          schema:
            $ref: "#/definitions/ErrorResponse"
  ###### Add ############################
  /userLists:
    x-swagger-router-controller: table # file: table.ts
    get:
      summary: Gets some persons
      operationId: getTable  # method: getTable
      description: Returns a list containing all persons.
      # request params
      parameters:
        - name: startDate
          in: query
          description: '搜索开始日期'
          required: false
          type: string
        - name: endDate
          in: query
          description: '搜索结束日期'
          required: false
          type: string
        - name: user
          in: query
          description: '搜索用户名'
          required: false
          type: string
      responses:
        200:
          description: A list of Person is Ok
          schema:
            type: object
            properties:
              status:
                type: integer
                format: int32
              data:
                type: object
                properties:
                  items:
                    type: array
                    items:
                      $ref: '#/definitions/Lists'
        # responses may fall through to errors
        default:
          description: Error
          schema:
            $ref: "#/definitions/ErrorResponse"
          # schema:
          #   type: array
          #   items:
          #     required:
          #       - name
          #     properties:
          #       name:
          #         type: string
          #       age:
          #         type: integer
          #         format: int32
          #       ip:
          #         type: string
          #       address:
          #         type: string
          #       date:
          #         type: string
  ###### Add ############################
  /swagger:
    x-swagger-pipe: swagger_raw
# complex objects have schema definitions
definitions:
  HelloWorldResponse:
    required:
      - message
    properties:
      message:
        type: string
  ErrorResponse:
    required:
      - message
    properties:
      message:
        type: string
  Lists:
    type: object
    required:
      - name
    properties:
      name:
        type: string
      age:
        type: integer
        format: int32
      ip:
        type: string
      address:
        type: string
      date:
        type: string